name: mapbox_maps_example
description: Demonstrates how to use the Mapbox Maps Flutter SDK.
version: "1.0.0-beta.1"

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_card_swiper: ^2.0.4
  smooth_page_indicator: ^1.0.0
  carousel_slider: ^4.2.1

  flutter_dotenv: ^5.0.2
  pointycastle: ^3.0.6
  cupertino_icons: ^1.0.2
  permission_handler: ^10.0.0
  font_awesome_flutter: ^10.1.0
  http: ^0.13.5
  path_provider: ^2.1.3
  mapbox_maps_flutter: ^2.4.1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_svg: ^2.0.9
  image_picker: ^1.1.2
  path: ^1.9.0
  sqflite: ^2.4.1
  intl: ^0.19.0
  flutter_sound: ^9.17.8
  animated_bottom_navigation_bar: ^1.3.3


dev_dependencies:
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.6.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/
    - assets/symbols/
    - assets/cluster/
    - assets/globe_johane.png
    - assets/book.png
    - assets/cogwheel.png
    - assets/earth.png
    - assets/user.png
    - assets/icons/calendar.svg
    - assets/icons/edit-2.svg
    - assets/icons/gallery.svg
    - assets/icons/message-text.svg
    - assets/icons/microphone-2.svg
    - assets/icons/user.svg
    - assets/icons/location.svg
    - assets/icons/share.png

    - assets/dagobert.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages